// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Grid from "../backend/Grid.res.mjs";
import * as Simulation from "../backend/Simulation.res.mjs";

let createSimulation = Simulation.create;

let stepSimulation = Simulation.step;

let getCell = Grid.getCell;

let isInside = Grid.isInside;

export {
  createSimulation,
  stepSimulation,
  getCell,
  isInside,
}
/* No side effect */
