// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Grid from "./Grid.res.mjs";
import * as Robot from "./Robot.res.mjs";

function simpleStep(sim) {
  let nextPos = Robot.nextPosition(sim.robot);
  if (Grid.isInside(sim.grid, nextPos)) {
    return "MoveForward";
  } else {
    return "TurnRight";
  }
}

export {
  simpleStep,
}
/* No side effect */
