// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Stdlib_Array from "@rescript/runtime/lib/es6/Stdlib_Array.js";

function create(size) {
  return Stdlib_Array.make(size, Stdlib_Array.make(size, "Dirty"));
}

function isInside(grid, pos) {
  let size = grid.length;
  if (pos.x >= 0 && pos.y >= 0 && pos.x < size) {
    return pos.y < size;
  } else {
    return false;
  }
}

function getCell(grid, pos) {
  let row = grid[pos.y];
  if (row === undefined) {
    return;
  }
  let cell = row[pos.x];
  if (cell !== undefined) {
    return cell;
  }
}

function cleanCell(grid, pos) {
  let row = grid[pos.y];
  if (row === undefined) {
    return;
  }
  let match = row[pos.x];
  if (match !== undefined) {
    row[pos.x] = "Clean";
    return;
  }
}

export {
  create,
  isInside,
  getCell,
  cleanCell,
}
/* No side effect */
