// Generated by ReScript, PLEASE EDIT WITH CARE


function create(startPos) {
  return {
    position: startPos,
    direction: "North"
  };
}

function turnLeft(robot) {
  let match = robot.direction;
  let newDirection;
  switch (match) {
    case "North" :
      newDirection = "West";
      break;
    case "South" :
      newDirection = "East";
      break;
    case "East" :
      newDirection = "North";
      break;
    case "West" :
      newDirection = "South";
      break;
  }
  return {
    position: robot.position,
    direction: newDirection
  };
}

function turnRight(robot) {
  let match = robot.direction;
  let newDirection;
  switch (match) {
    case "North" :
      newDirection = "East";
      break;
    case "South" :
      newDirection = "West";
      break;
    case "East" :
      newDirection = "South";
      break;
    case "West" :
      newDirection = "North";
      break;
  }
  return {
    position: robot.position,
    direction: newDirection
  };
}

function nextPosition(robot) {
  let match = robot.direction;
  switch (match) {
    case "North" :
      return {
        x: robot.position.x,
        y: robot.position.y - 1 | 0
      };
    case "South" :
      return {
        x: robot.position.x,
        y: robot.position.y + 1 | 0
      };
    case "East" :
      return {
        x: robot.position.x + 1 | 0,
        y: robot.position.y
      };
    case "West" :
      return {
        x: robot.position.x - 1 | 0,
        y: robot.position.y
      };
  }
}

function moveForward(robot) {
  let newPos = nextPosition(robot);
  return {
    position: newPos,
    direction: robot.direction
  };
}

export {
  create,
  turnLeft,
  turnRight,
  nextPosition,
  moveForward,
}
/* No side effect */
