// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Grid from "./Grid.res.mjs";
import * as Robot from "./Robot.res.mjs";
import * as Algorithm from "./Algorithm.res.mjs";

function create(size) {
  let initialGrid = Grid.create(size);
  let initialRobot = Robot.create({
    x: 0,
    y: 0
  });
  return {
    grid: initialGrid,
    robot: initialRobot
  };
}

function step(sim) {
  Grid.cleanCell(sim.grid, sim.robot.position);
  let action = Algorithm.simpleStep(sim);
  let updatedRobot;
  switch (action) {
    case "MoveForward" :
      updatedRobot = Robot.moveForward(sim.robot);
      break;
    case "TurnLeft" :
      updatedRobot = Robot.turnLeft(sim.robot);
      break;
    case "TurnRight" :
      updatedRobot = Robot.turnRight(sim.robot);
      break;
  }
  return {
    grid: sim.grid,
    robot: updatedRobot
  };
}

export {
  create,
  step,
}
/* No side effect */
