// Generated by ReScript, PLEASE EDIT WITH CARE

import * as JsxRuntime from "react/jsx-runtime";

function ControlPanel(props) {
  let isRunning = props.isRunning;
  let onReset = props.onReset;
  let onStep = props.onStep;
  let onPause = props.onPause;
  let onStart = props.onStart;
  return JsxRuntime.jsxs("div", {
    children: [
      JsxRuntime.jsx("button", {
        children: "Démarrer",
        className: "px-6 py-2 bg-green-500 text-white font-bold rounded hover:bg-green-600 disabled:bg-gray-400 disabled:cursor-not-allowed",
        disabled: isRunning,
        onClick: param => onStart()
      }),
      JsxRuntime.jsx("button", {
        children: "Pause",
        className: "px-6 py-2 bg-yellow-500 text-white font-bold rounded hover:bg-yellow-600 disabled:bg-gray-400 disabled:cursor-not-allowed",
        disabled: !isRunning,
        onClick: param => onPause()
      }),
      JsxRuntime.jsx("button", {
        children: "Pas suivant",
        className: "px-6 py-2 bg-blue-500 text-white font-bold rounded hover:bg-blue-600 disabled:bg-gray-400 disabled:cursor-not-allowed",
        disabled: isRunning,
        onClick: param => onStep()
      }),
      JsxRuntime.jsx("button", {
        children: "Réinitialiser",
        className: "px-6 py-2 bg-red-500 text-white font-bold rounded hover:bg-red-600",
        onClick: param => onReset()
      })
    ],
    className: "flex gap-4 justify-center my-6"
  });
}

let make = ControlPanel;

export {
  make,
}
/* react/jsx-runtime Not a pure module */
