// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Grid from "../backend/Grid.res.mjs";
import * as CellView from "./CellView.res.mjs";
import * as Stdlib_Array from "@rescript/runtime/lib/es6/Stdlib_Array.js";
import * as JsxRuntime from "react/jsx-runtime";

function GridView(props) {
  let robot = props.robot;
  let grid = props.grid;
  let gridHeight = grid.length;
  let row = grid[0];
  let gridWidth = row !== undefined ? row.length : 0;
  let cells = Stdlib_Array.make(gridHeight * gridWidth | 0, null);
  for (let y = 0; y < gridHeight; ++y) {
    for (let x = 0; x < gridWidth; ++x) {
      let pos = {
        x: x,
        y: y
      };
      let isRobot = robot.position.x === x && robot.position.y === y;
      let state = Grid.getCell(grid, pos);
      let cellState = state !== undefined ? state : "Dirty";
      let index = (y * gridWidth | 0) + x | 0;
      let robotDir = isRobot ? robot.direction : undefined;
      cells[index] = JsxRuntime.jsx(CellView.make, {
        cellState: cellState,
        isRobot: isRobot,
        robotDirection: robotDir
      }, index.toString());
    }
  }
  return JsxRuntime.jsx("div", {
    children: cells,
    className: "inline-grid gap-1 p-6 bg-gray-100 rounded-lg shadow-md",
    style: {
      gridTemplateColumns: `repeat(` + gridWidth.toString() + `, minmax(0, 1fr))`
    }
  });
}

let make = GridView;

export {
  make,
}
/* CellView Not a pure module */
