// Generated by ReScript, PLEASE EDIT WITH CARE

import * as JsxRuntime from "react/jsx-runtime";

function RobotView(props) {
  let match = props.robot.direction;
  let icon;
  switch (match) {
    case "North" :
      icon = "⬆️";
      break;
    case "South" :
      icon = "⬇️";
      break;
    case "East" :
      icon = "➡️";
      break;
    case "West" :
      icon = "⬅️";
      break;
  }
  return JsxRuntime.jsx("div", {
    children: icon,
    className: "text-2xl font-bold"
  });
}

let make = RobotView;

export {
  make,
}
/* react/jsx-runtime Not a pure module */
