// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as GridView from "./GridView.res.mjs";
import * as ControlPanel from "./ControlPanel.res.mjs";
import * as SimulationState from "../state/SimulationState.res.mjs";
import * as JsxRuntime from "react/jsx-runtime";

function SimulationView(props) {
  let match = SimulationState.useSimulationState();
  let reset = match[2];
  let step = match[1];
  let sim = match[0];
  let match$1 = React.useState(() => false);
  let setIsRunning = match$1[1];
  let isRunning = match$1[0];
  let timerRef = React.useRef(undefined);
  let handleStart = () => {
    setIsRunning(param => true);
    let id = setInterval(() => step(), 500);
    timerRef.current = id;
  };
  let handlePause = () => {
    setIsRunning(param => false);
    let id = timerRef.current;
    if (id !== undefined) {
      clearInterval(id);
      timerRef.current = undefined;
      return;
    }
  };
  let handleStep = () => step();
  let handleReset = () => {
    handlePause();
    reset();
  };
  React.useEffect(() => (() => {
    let id = timerRef.current;
    if (id !== undefined) {
      clearInterval(id);
      return;
    }
  }), []);
  return JsxRuntime.jsxs("div", {
    children: [
      JsxRuntime.jsx("h1", {
        children: "🤖 Robot Cleaner",
        className: "text-4xl font-bold text-blue-600 mb-8"
      }),
      JsxRuntime.jsx("div", {
        children: JsxRuntime.jsx(GridView.make, {
          grid: sim.grid,
          robot: sim.robot
        }),
        className: "mb-8"
      }),
      JsxRuntime.jsx(ControlPanel.make, {
        onStart: handleStart,
        onPause: handlePause,
        onStep: handleStep,
        onReset: handleReset,
        isRunning: isRunning
      }),
      JsxRuntime.jsxs("div", {
        children: [
          JsxRuntime.jsx("p", {
            children: "Statistiques:",
            className: "text-lg font-semibold mb-2"
          }),
          JsxRuntime.jsxs("p", {
            children: [
              "Position: (",
              sim.robot.position.x.toString(),
              ", ",
              sim.robot.position.y.toString(),
              ")"
            ],
            className: "text-gray-600"
          }),
          JsxRuntime.jsxs("p", {
            children: [
              "État: ",
              isRunning ? "En cours..." : "Arrêté"
            ],
            className: "text-gray-600"
          })
        ],
        className: "mt-8 p-6 bg-white rounded-lg shadow-md max-w-md"
      })
    ],
    className: "flex flex-col items-center justify-center min-h-screen bg-gray-50"
  });
}

let make = SimulationView;

export {
  make,
}
/* react Not a pure module */
