// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Simulation from "../backend/Simulation.res.mjs";
import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.js";
import * as Primitive_option from "@rescript/runtime/lib/es6/Primitive_option.js";

function useSimulationState() {
  let match = React.useState(() => Simulation.create(5));
  let setSim = match[1];
  let step = () => setSim(Simulation.step);
  let reset = () => setSim(param => Simulation.create(5));
  let timerRef = React.useRef(undefined);
  let start = () => {
    if (!Stdlib_Option.isNone(timerRef.current)) {
      return;
    }
    let id = setInterval(() => setSim(Simulation.step), 500);
    timerRef.current = Primitive_option.some(id);
  };
  let pause = () => {
    let id = timerRef.current;
    if (id !== undefined) {
      clearInterval(Primitive_option.valFromOption(id));
      timerRef.current = undefined;
      return;
    }
  };
  return [
    match[0],
    step,
    reset,
    start,
    pause
  ];
}

let defaultSize = 5;

export {
  defaultSize,
  useSimulationState,
}
/* react Not a pure module */
