// Generated by ReScript, PLEASE EDIT WITH CARE

import * as SimulationView from "./frontend/SimulationView.res.mjs";
import * as JsxRuntime from "react/jsx-runtime";

function App(props) {
  return JsxRuntime.jsx(SimulationView.make, {});
}

let make = App;

export {
  make,
}
/* SimulationView Not a pure module */
