// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Grid from "./backend/Grid.res.mjs";
import * as GridView from "./frontend/GridView.res.mjs";
import * as Simulation from "./backend/Simulation.res.mjs";
import * as SimulationState from "./state/SimulationState.res.mjs";
import * as JsxRuntime from "react/jsx-runtime";

function App(props) {
  let match = SimulationState.useSimulationState();
  let dispatch = match[1];
  let state = match[0];
  let sim = state.simulation;
  return JsxRuntime.jsx("div", {
    children: JsxRuntime.jsxs("div", {
      children: [
        JsxRuntime.jsx("h1", {
          children: "🤖 Robot Nettoyeur",
          className: "text-4xl font-bold text-center text-gray-800 mb-8"
        }),
        JsxRuntime.jsxs("div", {
          children: [
            JsxRuntime.jsx("h2", {
              children: "Statistiques",
              className: "text-2xl font-semibold mb-4"
            }),
            JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsxs("div", {
                  children: [
                    JsxRuntime.jsx("span", {
                      children: "🔋 Batterie: ",
                      className: "text-gray-600"
                    }),
                    JsxRuntime.jsx("span", {
                      children: sim.battery.toString() + `%`,
                      className: "font-bold text-xl text-green-600"
                    })
                  ]
                }),
                JsxRuntime.jsxs("div", {
                  children: [
                    JsxRuntime.jsx("span", {
                      children: "⭐ Score: ",
                      className: "text-gray-600"
                    }),
                    JsxRuntime.jsx("span", {
                      children: sim.score.toString(),
                      className: "font-bold text-xl text-indigo-600"
                    })
                  ]
                }),
                JsxRuntime.jsxs("div", {
                  children: [
                    JsxRuntime.jsx("span", {
                      children: "👣 Pas: ",
                      className: "text-gray-600"
                    }),
                    JsxRuntime.jsx("span", {
                      children: sim.steps.toString(),
                      className: "font-bold text-xl"
                    })
                  ]
                }),
                JsxRuntime.jsxs("div", {
                  children: [
                    JsxRuntime.jsx("span", {
                      children: "🧹 Restant: ",
                      className: "text-gray-600"
                    }),
                    JsxRuntime.jsx("span", {
                      children: Grid.countDirtyCells(sim.grid).toString(),
                      className: "font-bold text-xl text-red-600"
                    })
                  ]
                })
              ],
              className: "grid grid-cols-2 gap-4"
            })
          ],
          className: "bg-white rounded-lg shadow-lg p-6 mb-6"
        }),
        JsxRuntime.jsx("div", {
          children: JsxRuntime.jsx(GridView.make, {
            grid: sim.grid,
            robot: sim.robot
          }),
          className: "flex justify-center mb-6"
        }),
        JsxRuntime.jsxs("div", {
          children: [
            JsxRuntime.jsx("h2", {
              children: "Contrôles",
              className: "text-2xl font-semibold mb-4"
            }),
            JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsx("button", {
                  children: "➡️ Un Pas",
                  className: "px-6 py-3 bg-blue-500 hover:bg-blue-600 text-white rounded-lg font-semibold disabled:bg-gray-300 disabled:cursor-not-allowed",
                  disabled: Simulation.isFinished(sim) || state.isRunning,
                  onClick: param => dispatch("Tick")
                }),
                state.isRunning ? JsxRuntime.jsx("button", {
                    children: "⏸️ Pause",
                    className: "px-6 py-3 bg-orange-500 hover:bg-orange-600 text-white rounded-lg font-semibold",
                    onClick: param => dispatch("Pause")
                  }) : JsxRuntime.jsx("button", {
                    children: "▶️ Auto",
                    className: "px-6 py-3 bg-green-500 hover:bg-green-600 text-white rounded-lg font-semibold disabled:bg-gray-300 disabled:cursor-not-allowed",
                    disabled: Simulation.isFinished(sim),
                    onClick: param => dispatch("Start")
                  }),
                JsxRuntime.jsx("button", {
                  children: "🔄 Reset",
                  className: "px-6 py-3 bg-red-500 hover:bg-red-600 text-white rounded-lg font-semibold",
                  onClick: param => dispatch("Reset")
                })
              ],
              className: "flex flex-wrap gap-3"
            })
          ],
          className: "bg-white rounded-lg shadow-lg p-6"
        })
      ],
      className: "max-w-4xl mx-auto"
    }),
    className: "min-h-screen bg-gradient-to-br from-blue-50 to-indigo-100 p-8"
  });
}

let make = App;

export {
  make,
}
/* GridView Not a pure module */
